Jdp200101 2
pplutap/JDP-2001-01 pull request #2
Opened 2020-01-30 15:59 UTC by MajaBrog

Annotations added

2020-02-03 21:06 UTC, mryndak commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +@RequestMapping("v1/project")
proponował bym tutaj dopisać jeszcze /groups

2020-02-03 21:08 UTC, mryndak requested changes

2020-02-03 21:08 UTC, mryndak commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    @RequestMapping(method=RequestMethod.PUT, value="updateGroup")
Tutaj przydało by się przekazać id grupy lub utworzyć obiekt dto dla aktualizacji grupy

2020-02-04 16:46 UTC, MajaBrog commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    @RequestMapping(method=RequestMethod.PUT, value="updateGroup")
jako argument jest przekazywany String groupDto, który oczywiście poźniej będzie zamieniony na obiekt dto. Jednym z jego pól będzie jego Id więc po co je dodatkowo dodawać jako argument?

2020-02-05 09:47 UTC, mryndak commented
Endpointy powinny zwracać zamockowane dane

2020-02-05 20:59 UTC, mryndak approved these changes

2020-02-05 21:03 UTC, merged