Group entity - implementation with GroupRepository (JDP200101-13)
pplutap/JDP-2001-01 pull request #9
Opened 2020-02-09 17:38 UTC by deseff

2020-02-10 00:53 UTC, Olafbb reviewed
Według mnie wszystko gra. Jedynie to kwestia adnotacji, czyli musimy się ugadać czy robimy je przy akcesorach czy przy polach 👍

2020-02-10 22:19 UTC, Skorpien commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@AllArgsConstructor
sorki, że ja się  tutaj wtrącę, ale wydaje mi się, że użycie @AllArgsConstructor może być tu trochę zgubne. Wydaje mi się, że wtedy do konstruktora wrzuca też private List<Product> products.
Tak więc masz albo bezparametrowy, albo 3 parametrowy (Long id, String name, List<Product> products), a tego trzeciego nie wiem czy jest sens w konstruktor wrzucać ;)

2020-02-12 06:28 UTC, MARudnicki requested changes

2020-02-12 06:28 UTC, MARudnicki commented on build.gradle
> +    compileOnly('org.projectlombok:lombok')
implementation oraz compile znaczy to samo. Warto trzymac sie jednek skladni
https://stackoverflow.com/a/44493379

2020-02-12 20:13 UTC, deseff commented on build.gradle
> +    compileOnly('org.projectlombok:lombok')
Zmienione

2020-02-12 20:13 UTC, deseff commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@AllArgsConstructor
Słuszna uwaga.

2020-02-13 06:24 UTC, MARudnicki approved these changes

2020-02-13 19:45 UTC, merged